version: '3.8'

services:
  # user db
  identity-db:
    image: postgres:16-alpine
    container_name: pawsstay-identity-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: pawsstay_identity
    ports:
      - "5432:5432"
    volumes:
      - identity_db_data:/var/lib/postgresql/data
    networks:
      - pawsstay-network

  # in the future
  cache:
    image: redis:7-alpine
    container_name: pawsstay-redis
    ports:
      - "6379:6379"
    networks:
      - pawsstay-network

networks:
  pawsstay-network:
    driver: bridge

volumes:
  identity_db_data: